server:
  port: 2604

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/candidate
    username: postgres
    password: joel1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true